### ISSUE TITLE
Decimals should be trimmed

### ISSUE THREAD

**Issue by RandomlyKnighted** [noazark/weather#10]
Per PR #9 when using `forecast.low()`, `forecast.high()`, `Weather.kelvinToFahrenheit()`, and `Weather.kelvinToCelsius()` decimals somtimes look like this `25.584000000000003`. I haven't looked into it yet to see which function is causing the issue, but it probably wouldn't hurt to trim the decimals on all four methods. We can go to the hundredths place like so `25.58` or we could just round it up to the nearest whole number.

**Comment by noazark** [comment]
This is a common problem with floating point calculations and is unavoidable without special handling (which is beyond scope of this library). [This thread sums it up nicely](http://programmers.stackexchange.com/questions/101163/what-causes-floating-point-rounding-errors). One of the reasons I think weather.js should drop all conversion helpers is for this reason, other libraries simply do a better job of it than I am willing to.

**Comment by RandomlyKnighted** [comment]
Well it wouldn't have to be anything complicated. This could be easily done with `Math.round()`. For example if we want to round to 2 decimal places then we could use the following: `Math.round(value * 100) / 100`

**Comment by noazark** [comment]
Rounding doesn't actually fix the error though and will make other calculations less precise. `.333333333333 != .33`

**Comment by noazark** [comment]
BTW, there are libraries out there that do floating point calculations more precisely (albeit they're more costly on the CPU). Take a look at [bignumber.js](https://mikemcl.github.io/bignumber.js/).

**Comment by RandomlyKnighted** [comment]
@noazark any chance we could have a Hangouts or Skype session? I think we're both different pages with some of this and it would be good if I could get a clearer understanding of your goals.

**Comment by noazark** [comment]
Just sent a Hangouts invite
