### ISSUE TITLE
Weather.getCurrent not working

### ISSUE THREAD

**Issue by Waleed101** [noazark/weather#22]
Weather.getCurrent doesn't work. When changing it to a different city (e.g. London) it stays the same

``` javascript
<script>
        Weather.getCurrent( "London", function( current ) {
            $( "#current" ).html( "Temperature: " + current.temperature() + "&deg;K or " +
                Weather.kelvinToFahrenheit( current.temperature() ) + "&deg;F or " +
                Weather.kelvinToCelsius( current.temperature() ) + "&deg;C" +
                "<br />Current Conditions: " + current.conditions() );
        });
        Weather.getForecast( "London", function ( forecast ) {
            $( "#forecast" ).html( "High: " + forecast.high() + "&deg;K or " +
                Weather.kelvinToFahrenheit( forecast.high() ) + "&deg;F or " +
                Weather.kelvinToCelsius( forecast.high() ) + "&deg;C<br />Low: " +
                forecast.low() + "&deg;K or " +
                Weather.kelvinToFahrenheit( forecast.low() ) + "&deg;F or " +
                Weather.kelvinToCelsius( forecast.low() ) + "&deg;C" );
        });
</script>`
```

**Comment by RandomlyKnighted** [comment]
Sorry for the delay, I just got a chance to look at this in detail. As it turns out OpenWeatherMap recently dropped support for v2.1 of their API.  That's the version we are currently using in OpenWeatherMap. We've got a release planned for this week; however, this release will still be for the v2.1 API. I hope to have a release 2nd release in the next couple weeks that fixes this issue and makes weather.js usable again.

**Comment by titimoby** [comment]
@noazark nice job in this library.
I saw the next branch and it seems that you made quick progress.
Do you know when you will be able to release the new API? (roughly, to have an estimate)

**Comment by RandomlyKnighted** [comment]
To my knowledge we don't have a date set it but it should be pretty soon.

**Comment by noazark** [comment]
@RandomlyKnighted is correct. Unfortunately no solid date. I am working on it more consistently now though so I'll get it out asap.

**Comment by lsterling03** [comment]
Is this fixed? I'm considering using weather.js.

**Comment by RandomlyKnighted** [comment]
@noazark how close are you to completing the next version?

**Comment by joZephhh** [comment]
any news ?

**Comment by jmoalves** [comment]
I believe my pull request also closes this issue.
https://github.com/noazark/weather/pull/27

**Comment by Dzonny** [comment]
@jmoalves I just tried main branch with your edits in weather.js file from your latest PR, but not working on my end.

**Comment by jmoalves** [comment]
@Dzonny I found some jshint errors and fixed them. I also added a call for with the apikey in the current.js tests. Besides this, I found no errors in the new code. Could you check if it is alright now?

**Comment by Dzonny** [comment]
@jmoalves I just set the apikey in the current.js file, and still got nothing when I try to load examples index.html file, just got plain "Guntersville, AL - Current Conditions - Forecast" text. Not sure if I'm doing something wrong though.

**Comment by jmoalves** [comment]
I used the attached index.html to test.
[index.html.zip](https://github.com/noazark/weather/files/908774/index.html.zip)

I was able to get some results.
Perhaps I am doing something wrong... 
Could you try the attached index.html file with your api key?

I got these results in the console:
Rio de Janeiro - Forecast High in Kelvin: 296.25
Rio de Janeiro - Forecast High in Fahrenheit: 73.58000000000004
Rio de Janeiro - Forecast High in Celsius: 23.100000000000023
Paris - Forecast High in Kelvin: 282.745
Paris - Forecast High in Fahrenheit: 49.27100000000005
Paris - Forecast High in Celsius: 9.595000000000027
Rio de Janeiro - currently: 296.25 and clear sky
New York - currently: 282.89 and few clouds
Paris - currently: 282.04 and clear sky
New York - Forecast High in Kelvin: 282.89
New York - Forecast High in Fahrenheit: 49.53200000000002
New York - Forecast High in Celsius: 9.740000000000009
London - currently: 280.35 and clear sky
London - Forecast High in Kelvin: 283.045
London - Forecast High in Fahrenheit: 49.81100000000007
London - Forecast High in Celsius: 9.895000000000039

**Comment by Dzonny** [comment]
Still no luck though.
Note that I'm sure that path to lib/weather.js is correct and API key is in place. Just blank page on my end.

Do note also that my API is working, I actually managed to make simple script in php to pull json data from API and display it nicely (although I'm still working on it), but I was just curious about this script as I'm not into the JS thing :)

**Comment by jmoalves** [comment]
I fixed the path for weather.js on examples/index.html.
With the correct apikey, I got the following results:
```
Guntersville, AL
Current Conditions
Temperature: 288.83°K or 60.22400000000002°F or 15.680000000000007°C
Current Conditions: clear sky
Forecast
High: 290.098°K or 62.50640000000007°F or 16.948000000000036°C
Low: 288.83°K or 60.22400000000002°F or 15.680000000000007°C

```
However, I found no errors in the weather.js file.
Could check the console log (in dev tools) and post the listed errors here?

Thanks.

**Comment by aaronxdd** [comment]
you need sign up for the apiKey

**Comment by PallasStreams** [comment]
The code currently in the master branch supports both API version 2.5 as well as using an API key.
