### ISSUE TITLE
Using https in API URL

### ISSUE THREAD

**Issue by faheemhameed** [noazark/weather#32]
Hi there,

My site uses https but the weather.js sends api request to the api in http and the browser complaints about it.

ex: http://api.openweathermap.org/data ...

Is it possible that I can configure or do something to change http to https in the api URLs that the weather.js uses?

Thanks.

**Comment by dave-highaltitude** [comment]
@faheemhameed - I've submitted a pull request to fix this. In the meantime, you can edit the API url at either `dist/weather.js` or `lib/weather.js` depending on which you're using.

**Comment by faheemhameed** [comment]
Thanks @dave-highaltitude for your help! Taking your suggestion...
