### ISSUE TITLE
Is there any documentation beyond the basic two calls found in the readme?

### ISSUE THREAD

**Issue by idreeshaddad** [noazark/weather#4]

**Comment by RandomlyKnighted** [comment]
There are the following methods available:

- kelvinToFahrenheit
- kelvinToCelsius
- getCurrent
- getForecast

**Comment by RandomlyKnighted** [comment]
@idreeshaddad @spencerthayer I've updated the readme so the forecast method now includes an example of the `kelvinToFahrenheit` and `kelvinToCelsius` methods.

**Comment by noazark** [comment]
Thanks @RandomlyKnighted, I will also try to get some inline documentation going. Will leave this issue open until that's finished.

**Comment by PallasStreams** [comment]
In my most recent PR I have updated the README to include examples of how to use all of the methods mentioned above.
